import { spawn, execFileSync, type ChildProcessWithoutNullStreams } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";
import type {
  AggregatorReport,
  AggregatorReportIntegrityCheck,
  InvalidVoteReason
} from "../packages/shared/src/index.ts";

const projectRoot = fileURLToPath(new URL("..", import.meta.url));
const reportDir = join(projectRoot, "docs", "evaluation", "aggregator_reports");
const tempDir = join(projectRoot, ".codex_tmp");
const port = 38000 + Math.floor(Math.random() * 1000);
const baseUrl = `http://127.0.0.1:${port}`;

interface JsonResponse<T> {
  status: number;
  body: T;
}

interface SmokeExpectation {
  totalVotes: number;
  validVotes: number;
  invalidVotes: number;
  duplicateVotes: number;
  receiptChainVerified: boolean;
  reasons: InvalidVoteReason[];
}

interface SmokeCaseResult {
  name: string;
  endpoint: string;
  status: number;
  apiReportFile: string;
  apiAttackAliasFile: string | null;
  integrityVerified: boolean;
  failures: string[];
  reportSummary: {
    totalVotes: number;
    validVotes: number;
    invalidVotes: number;
    duplicateVotes: number;
    proofStatus: string;
    receiptChainVerified: boolean;
    reasons: string[];
    validVoteIds: string[];
    invalidVoteIds: string[];
    partitionHash: string;
    diagnosticsHash: string;
    auditHash: string;
  };
}

interface ReportTamperSmokeResult {
  name: string;
  endpoint: string;
  status: number;
  reportStatus: number;
  integrityVerified: boolean;
  expectedIntegrityFailures: string[];
  observedFailures: string[];
  tallyConsistent: boolean;
  consistencyMessage: string;
  auditHash: string;
  file: string;
}

function writeJson(filePath: string, value: unknown): void {
  writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function assertCase(
  label: string,
  condition: boolean,
  details?: Record<string, unknown>
): void {
  if (!condition) {
    throw new Error(`${label} failed${details ? `: ${JSON.stringify(details)}` : ""}`);
  }
  console.log(`PASS ${label}`);
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function requestJson<T>(
  method: "GET" | "POST",
  path: string,
  body?: unknown
): Promise<JsonResponse<T>> {
  const response = await fetch(`${baseUrl}${path}`, {
    method,
    headers: body === undefined ? undefined : { "Content-Type": "application/json" },
    body: body === undefined ? undefined : JSON.stringify(body)
  });
  const text = await response.text();
  let parsed: T;
  try {
    parsed = text ? (JSON.parse(text) as T) : ({} as T);
  } catch (error) {
    throw new Error(
      `${method} ${path} returned non-JSON status ${response.status}: ${text.slice(0, 200)}`,
      { cause: error }
    );
  }
  return { status: response.status, body: parsed };
}

async function waitForHealth(server: ChildProcessWithoutNullStreams): Promise<void> {
  const stderr: string[] = [];
  server.stderr.on("data", (chunk) => stderr.push(String(chunk)));

  for (let attempt = 0; attempt < 80; attempt += 1) {
    if (server.exitCode !== null) {
      throw new Error(`API exited early with code ${server.exitCode}: ${stderr.join("")}`);
    }

    try {
      const response = await requestJson<{ ok: boolean }>("GET", "/health");
      if (response.status === 200 && response.body.ok) {
        return;
      }
    } catch {
      // Server is still starting.
    }

    await sleep(250);
  }

  throw new Error(`Timed out waiting for ${baseUrl}/health`);
}

function stopServer(server: ChildProcessWithoutNullStreams): void {
  if (server.exitCode !== null) {
    return;
  }

  if (process.platform === "win32") {
    execFileSync("taskkill", ["/PID", String(server.pid), "/T", "/F"], {
      stdio: "ignore"
    });
    return;
  }

  server.kill("SIGTERM");
}

async function startApiServer(
  env: Record<string, string>
): Promise<ChildProcessWithoutNullStreams> {
  const tsxCli = join(
    projectRoot,
    "node_modules",
    ".pnpm",
    "tsx@4.21.0",
    "node_modules",
    "tsx",
    "dist",
    "cli.cjs"
  );
  const server = spawn(
    process.execPath,
    [tsxCli, "apps/api/src/index.ts"],
    {
      cwd: projectRoot,
      env: {
        ...process.env,
        PORT: String(port),
        ...env
      },
      stdio: ["ignore", "pipe", "pipe"]
    }
  );

  await waitForHealth(server);
  return server;
}

async function seedElection(name: string): Promise<string> {
  const electionResponse = await requestJson<{ election: { id: string } }>(
    "POST",
    "/elections",
    {
      title: `A-track API smoke ${name}`,
      description: "Generated by pnpm aggregator:api-smoke"
    }
  );
  assertCase(`${name}: create election`, electionResponse.status === 201, {
    status: electionResponse.status,
    body: electionResponse.body
  });
  const electionId = electionResponse.body.election.id;

  const candidateIds: string[] = [];
  for (const candidateName of ["Alice", "Bob", "Carol", "Dave"]) {
    const candidateResponse = await requestJson<{ candidate: { id: string } }>(
      "POST",
      `/elections/${electionId}/candidates`,
      { name: candidateName }
    );
    assertCase(`${name}: create candidate ${candidateName}`, candidateResponse.status === 201, {
      status: candidateResponse.status,
      body: candidateResponse.body
    });
    candidateIds.push(candidateResponse.body.candidate.id);
  }

  for (let index = 0; index < 8; index += 1) {
    const userResponse = await requestJson<{ userId: string }>(
      "POST",
      "/users/register",
      { name: `${name} user ${index + 1}` }
    );
    assertCase(`${name}: create user ${index + 1}`, userResponse.status === 201, {
      status: userResponse.status,
      body: userResponse.body
    });

    const voteResponse = await requestJson<{ voteId: string }>(
      "POST",
      `/elections/${electionId}/vote`,
      {
        userId: userResponse.body.userId,
        candidateId: candidateIds[index % candidateIds.length]
      }
    );
    assertCase(`${name}: cast vote ${index + 1}`, voteResponse.status === 201, {
      status: voteResponse.status,
      body: voteResponse.body
    });
  }

  return electionId;
}

function diagnosticReasons(report: AggregatorReport): string[] {
  return Array.from(
    new Set(report.invalidVoteDiagnostics.map((diagnostic) => diagnostic.reason))
  ).sort();
}

function jsonEqual(left: unknown, right: unknown): boolean {
  return JSON.stringify(left) === JSON.stringify(right);
}

function assertReport(
  name: string,
  report: AggregatorReport,
  integrityCheck: AggregatorReportIntegrityCheck,
  expectation: SmokeExpectation
): void {
  assertCase(`${name}: integrity`, integrityCheck.verified, {
    failures: integrityCheck.failures
  });
  assertCase(`${name}: totalVotes`, report.totalVotes === expectation.totalVotes, {
    actual: report.totalVotes,
    expected: expectation.totalVotes
  });
  assertCase(`${name}: validVotes`, report.validVotes === expectation.validVotes, {
    actual: report.validVotes,
    expected: expectation.validVotes
  });
  assertCase(`${name}: invalidVotes`, report.invalidVotes === expectation.invalidVotes, {
    actual: report.invalidVotes,
    expected: expectation.invalidVotes
  });
  assertCase(`${name}: duplicateVotes`, report.duplicateVotes === expectation.duplicateVotes, {
    actual: report.duplicateVotes,
    expected: expectation.duplicateVotes
  });
  assertCase(
    `${name}: receiptChainVerified`,
    report.receiptChainVerified === expectation.receiptChainVerified,
    {
      actual: report.receiptChainVerified,
      expected: expectation.receiptChainVerified
    }
  );
  assertCase(
    `${name}: proofStatus placeholder`,
    report.proofStatus === "not-generated" &&
      report.tallyProofSummary?.proofStatus === "not-generated" &&
      report.tallyProofSummary.proofId === null,
    {
      proofStatus: report.proofStatus,
      tallyProofSummary: report.tallyProofSummary
    }
  );

  const bucketVoteIds = report.partitionAudit.buckets.flatMap((bucket) => bucket.voteIds);
  const bucketVoteIdSet = new Set(bucketVoteIds);
  const diagnosticVoteIds = Array.from(
    new Set(report.invalidVoteDiagnostics.map((diagnostic) => diagnostic.voteId))
  ).sort();
  assertCase(
    `${name}: API validVoteIds match bucket ids`,
    report.validVoteIds.length === bucketVoteIds.length &&
      report.validVoteIds.every((voteId) => bucketVoteIdSet.has(voteId)),
    {
      validVoteIds: report.validVoteIds,
      bucketVoteIds
    }
  );
  assertCase(
    `${name}: API invalidVoteIds match diagnostics`,
    JSON.stringify(report.invalidVoteIds.slice().sort()) === JSON.stringify(diagnosticVoteIds),
    {
      invalidVoteIds: report.invalidVoteIds,
      diagnosticVoteIds
    }
  );
  assertCase(
    `${name}: API invalid ids excluded from buckets`,
    report.invalidVoteIds.every((voteId) => !bucketVoteIdSet.has(voteId)),
    {
      invalidVoteIds: report.invalidVoteIds,
      bucketVoteIds
    }
  );

  const reasons = diagnosticReasons(report);
  for (const reason of expectation.reasons) {
    assertCase(`${name}: reason ${reason}`, reasons.includes(reason), { reasons });
  }
}

async function runAggregatorCase(
  name: string,
  attackEndpoint: string | null,
  expectation: SmokeExpectation
): Promise<SmokeCaseResult> {
  const electionId = await seedElection(name);
  let attackStatus = 0;

  if (attackEndpoint) {
    const attackResponse = await requestJson<{ ok: boolean }>(
      "POST",
      `/attack/elections/${electionId}/${attackEndpoint}`
    );
    attackStatus = attackResponse.status;
    assertCase(`${name}: attack endpoint ${attackEndpoint}`, attackResponse.status === 200, {
      status: attackResponse.status,
      body: attackResponse.body
    });
  }

  const runResponse = await requestJson<{
    report: AggregatorReport;
    integrityCheck: AggregatorReportIntegrityCheck;
  }>("POST", `/aggregator/elections/${electionId}/run`);
  assertCase(`${name}: run aggregator`, runResponse.status === 201, {
    status: runResponse.status,
    body: runResponse.body
  });
  assertReport(name, runResponse.body.report, runResponse.body.integrityCheck, expectation);

  const reportResponse = await requestJson<{
    report: AggregatorReport;
    integrityCheck: AggregatorReportIntegrityCheck;
  }>("GET", `/aggregator/elections/${electionId}/report`);
  assertCase(`${name}: get aggregator report`, reportResponse.status === 200, {
    status: reportResponse.status,
    body: reportResponse.body
  });
  assertReport(
    `${name} report endpoint`,
    reportResponse.body.report,
    reportResponse.body.integrityCheck,
    expectation
  );
  const apiReportFile = `api_aggregator_report.${name}.json`;
  const apiAttackAliasFile = attackEndpoint
    ? `api_aggregator_report.attack-${name}.json`
    : null;
  const apiReportEvidence = {
    schemaVersion: "verivote.aggregator-api-report-evidence.v1",
    generatedBy: "pnpm aggregator:api-smoke",
    name,
    runEndpoint: `/aggregator/elections/${electionId}/run`,
    reportEndpoint: `/aggregator/elections/${electionId}/report`,
    attackEndpoint: attackEndpoint
      ? `/attack/elections/${electionId}/${attackEndpoint}`
      : null,
    runStatus: runResponse.status,
    reportStatus: reportResponse.status,
    attackStatus: attackEndpoint ? attackStatus : null,
    report: runResponse.body.report,
    integrityCheck: runResponse.body.integrityCheck
  };
  writeJson(join(reportDir, apiReportFile), apiReportEvidence);
  if (apiAttackAliasFile) {
    writeJson(join(reportDir, apiAttackAliasFile), apiReportEvidence);
  }

  return {
    name,
    endpoint: attackEndpoint ? `/attack/elections/:id/${attackEndpoint}` : "/aggregator/elections/:id/run",
    status: attackEndpoint ? attackStatus : runResponse.status,
    apiReportFile: `docs/evaluation/aggregator_reports/${apiReportFile}`,
    apiAttackAliasFile: apiAttackAliasFile
      ? `docs/evaluation/aggregator_reports/${apiAttackAliasFile}`
      : null,
    integrityVerified: runResponse.body.integrityCheck.verified,
    failures: runResponse.body.integrityCheck.failures,
    reportSummary: {
      totalVotes: runResponse.body.report.totalVotes,
      validVotes: runResponse.body.report.validVotes,
      invalidVotes: runResponse.body.report.invalidVotes,
      duplicateVotes: runResponse.body.report.duplicateVotes,
      proofStatus: runResponse.body.report.proofStatus,
      receiptChainVerified: runResponse.body.report.receiptChainVerified,
      reasons: diagnosticReasons(runResponse.body.report),
      validVoteIds: runResponse.body.report.validVoteIds,
      invalidVoteIds: runResponse.body.report.invalidVoteIds,
      partitionHash: runResponse.body.report.partitionHash,
      diagnosticsHash: runResponse.body.report.diagnosticsHash,
      auditHash: runResponse.body.report.auditHash
    }
  };
}

async function runExportSmoke(): Promise<Record<string, unknown>> {
  const electionId = await seedElection("export");
  await requestJson("POST", `/aggregator/elections/${electionId}/run`);

  const aggregatorExport = await requestJson<{
    integrityCheck: AggregatorReportIntegrityCheck;
    auditHash: string;
    partitionHash: string;
    publicInputHints: { partitionHash: string; diagnosticsHash: string };
  }>("GET", `/elections/${electionId}/export/aggregator_report.json`);
  assertCase("export: aggregator_report.json", aggregatorExport.status === 200, {
    status: aggregatorExport.status,
    body: aggregatorExport.body
  });
  assertCase("export: aggregator report integrity", aggregatorExport.body.integrityCheck.verified, {
    failures: aggregatorExport.body.integrityCheck.failures
  });

  const publicInputsExport = await requestJson<{
    partitionHash: string;
    diagnosticsHash: string;
    auditHash: string;
    validVotes: number;
  }>("GET", `/elections/${electionId}/export/public_inputs.json`);
  assertCase("export: public_inputs.json", publicInputsExport.status === 200, {
    status: publicInputsExport.status,
    body: publicInputsExport.body
  });
  assertCase(
    "export: public inputs bind aggregator report",
    publicInputsExport.body.partitionHash === aggregatorExport.body.partitionHash &&
      publicInputsExport.body.diagnosticsHash ===
        aggregatorExport.body.publicInputHints.diagnosticsHash,
    {
      publicInputs: publicInputsExport.body,
      aggregator: aggregatorExport.body.publicInputHints
    }
  );
  const bundleExport = await requestJson<{
    bundle: {
      aggregatorReport: AggregatorReport | null;
      tallyProofSummary: AggregatorReport["tallyProofSummary"];
      chainAudit: { status: string };
      demoMetadata: { demoSeedFile: string };
    };
  }>("GET", `/elections/${electionId}/export-bundle`);
  assertCase("export: export-bundle", bundleExport.status === 200, {
    status: bundleExport.status,
    body: bundleExport.body
  });
  assertCase(
    "export: bundle carries A-track report and proof placeholder",
    bundleExport.body.bundle.aggregatorReport?.auditHash ===
      aggregatorExport.body.auditHash &&
      bundleExport.body.bundle.tallyProofSummary?.proofStatus ===
        "not-generated" &&
      bundleExport.body.bundle.demoMetadata.demoSeedFile ===
        "docs/contracts/demo_seed_fixture.json",
    {
      bundle: bundleExport.body.bundle,
      aggregatorExport: aggregatorExport.body
    }
  );
  const rawExportFiles = {
    aggregatorReport:
      "docs/evaluation/aggregator_reports/api_export_aggregator_report.json",
    publicInputs:
      "docs/evaluation/aggregator_reports/api_export_public_inputs.json",
    exportBundle:
      "docs/evaluation/aggregator_reports/api_export_bundle.json"
  };
  writeJson(
    join(reportDir, "api_export_aggregator_report.json"),
    aggregatorExport.body
  );
  writeJson(
    join(reportDir, "api_export_public_inputs.json"),
    publicInputsExport.body
  );
  writeJson(join(reportDir, "api_export_bundle.json"), bundleExport.body.bundle);

  return {
    electionId,
    aggregatorReportEndpoint: "/elections/:id/export/aggregator_report.json",
    publicInputsEndpoint: "/elections/:id/export/public_inputs.json",
    bundleEndpoint: "/elections/:id/export-bundle",
    rawExportFiles,
    aggregatorIntegrityVerified: aggregatorExport.body.integrityCheck.verified,
    publicInputs: publicInputsExport.body,
    bundle: {
      proofStatus: bundleExport.body.bundle.tallyProofSummary?.proofStatus,
      chainAuditStatus: bundleExport.body.bundle.chainAudit.status,
      demoSeedFile: bundleExport.body.bundle.demoMetadata.demoSeedFile,
      aggregatorAuditHash: bundleExport.body.bundle.aggregatorReport?.auditHash
    }
  };
}

async function runReportTamperSmoke(): Promise<ReportTamperSmokeResult> {
  const electionId = await seedElection("report-tamper");
  const runResponse = await requestJson<{
    report: AggregatorReport;
    integrityCheck: AggregatorReportIntegrityCheck;
  }>("POST", `/aggregator/elections/${electionId}/run`);
  assertCase("report-tamper: initial run", runResponse.status === 201, {
    status: runResponse.status,
    body: runResponse.body
  });
  assertCase("report-tamper: initial integrity", runResponse.body.integrityCheck.verified, {
    failures: runResponse.body.integrityCheck.failures
  });

  const attackResponse = await requestJson<{ ok: boolean }>(
    "POST",
    `/attack/elections/${electionId}/tamper-tally`
  );
  assertCase("report-tamper: attack endpoint tamper-tally", attackResponse.status === 200, {
    status: attackResponse.status,
    body: attackResponse.body
  });

  const reportResponse = await requestJson<{
    report: AggregatorReport;
    integrityCheck: AggregatorReportIntegrityCheck;
    tallyConsistent: boolean;
    consistencyMessage: string;
  }>("GET", `/aggregator/elections/${electionId}/report`);
  assertCase("report-tamper: get tampered report", reportResponse.status === 200, {
    status: reportResponse.status,
    body: reportResponse.body
  });
  assertCase(
    "report-tamper: integrity rejects recomputed auditHash tally tamper",
    reportResponse.body.integrityCheck.verified === false &&
      reportResponse.body.integrityCheck.checks.bucketTallyMatches === false &&
      reportResponse.body.integrityCheck.checks.tallyTotalMatchesValidVotes === false &&
      reportResponse.body.integrityCheck.checks.tallySumMatchesValidVotes === false,
    {
      integrityCheck: reportResponse.body.integrityCheck
    }
  );
  assertCase(
    "report-tamper: tally consistency detects saved report drift",
    reportResponse.body.tallyConsistent === false,
    {
      tallyConsistent: reportResponse.body.tallyConsistent,
      consistencyMessage: reportResponse.body.consistencyMessage
    }
  );

  const file = "api_aggregator_report.attack-tamper-tally.json";
  writeJson(join(reportDir, file), {
    schemaVersion: "verivote.aggregator-api-report-tamper-evidence.v1",
    generatedBy: "pnpm aggregator:api-smoke",
    name: "tamper-tally",
    endpoint: `/attack/elections/${electionId}/tamper-tally`,
    reportEndpoint: `/aggregator/elections/${electionId}/report`,
    attackStatus: attackResponse.status,
    reportStatus: reportResponse.status,
    report: reportResponse.body.report,
    integrityCheck: reportResponse.body.integrityCheck,
    tallyConsistent: reportResponse.body.tallyConsistent,
    consistencyMessage: reportResponse.body.consistencyMessage
  });

  return {
    name: "tamper-tally",
    endpoint: "/attack/elections/:id/tamper-tally",
    status: attackResponse.status,
    reportStatus: reportResponse.status,
    integrityVerified: reportResponse.body.integrityCheck.verified,
    expectedIntegrityFailures: [
      "bucketTallyMatches",
      "tallyTotalMatchesValidVotes",
      "tallySumMatchesValidVotes"
    ],
    observedFailures: reportResponse.body.integrityCheck.failures,
    tallyConsistent: reportResponse.body.tallyConsistent,
    consistencyMessage: reportResponse.body.consistencyMessage,
    auditHash: reportResponse.body.report.auditHash,
    file: `docs/evaluation/aggregator_reports/${file}`
  };
}

async function runPersistenceSmoke(): Promise<Record<string, unknown>> {
  mkdirSync(tempDir, { recursive: true });
  const sqlitePath = join(tempDir, `aggregator-api-smoke-${Date.now()}.db`);
  let firstServer: ChildProcessWithoutNullStreams | null = null;
  let secondServer: ChildProcessWithoutNullStreams | null = null;

  try {
    firstServer = await startApiServer({
      VERIVOTE_PERSISTENCE: "sqlite",
      VERIVOTE_SQLITE_PATH: sqlitePath
    });
    const electionId = await seedElection("persistence");
    const runResponse = await requestJson<{
      report: AggregatorReport;
      integrityCheck: AggregatorReportIntegrityCheck;
    }>("POST", `/aggregator/elections/${electionId}/run`);
    assertCase("persistence: initial run", runResponse.status === 201, {
      status: runResponse.status,
      body: runResponse.body
    });
    assertCase("persistence: initial integrity", runResponse.body.integrityCheck.verified, {
      failures: runResponse.body.integrityCheck.failures
    });
    const originalReport = runResponse.body.report;
    stopServer(firstServer);
    firstServer = null;
    await sleep(500);

    secondServer = await startApiServer({
      VERIVOTE_PERSISTENCE: "sqlite",
      VERIVOTE_SQLITE_PATH: sqlitePath
    });
    const loadedResponse = await requestJson<{
      report: AggregatorReport;
      integrityCheck: AggregatorReportIntegrityCheck;
    }>("GET", `/aggregator/elections/${electionId}/report`);
    assertCase("persistence: report survives restart", loadedResponse.status === 200, {
      status: loadedResponse.status,
      body: loadedResponse.body
    });
    assertCase("persistence: loaded integrity", loadedResponse.body.integrityCheck.verified, {
      failures: loadedResponse.body.integrityCheck.failures
    });
    assertCase(
      "persistence: v2 fields survive restart",
      loadedResponse.body.report.auditHash === originalReport.auditHash &&
        loadedResponse.body.report.validVoteIds.length ===
          originalReport.validVoteIds.length &&
        loadedResponse.body.report.invalidVoteIds.length ===
          originalReport.invalidVoteIds.length &&
        loadedResponse.body.report.proofStatus === originalReport.proofStatus &&
        loadedResponse.body.report.tallyProofSummary?.proofStatus ===
          originalReport.tallyProofSummary?.proofStatus &&
        loadedResponse.body.report.partitionAudit.buckets.every(
          (bucket) => Array.isArray(bucket.tokenHashes)
        ),
      {
        originalAuditHash: originalReport.auditHash,
        loadedAuditHash: loadedResponse.body.report.auditHash,
        loadedValidVoteIds: loadedResponse.body.report.validVoteIds,
        loadedInvalidVoteIds: loadedResponse.body.report.invalidVoteIds
      }
    );
    const persistentFieldNames: Array<keyof AggregatorReport> = [
      "electionId",
      "totalVotes",
      "validVotes",
      "validVoteIds",
      "invalidVotes",
      "invalidVoteIds",
      "duplicateVotes",
      "proofStatus",
      "tallyProofSummary",
      "receiptChainVerified",
      "receiptChainBreaks",
      "voteTokenHashes",
      "duplicateTokenHashes",
      "tallyResult",
      "commitmentRoot",
      "receiptRoot",
      "partitionAudit",
      "partitionHash",
      "invalidVoteDiagnostics",
      "diagnosticsHash",
      "publicInputHints",
      "pedersenAggregateAudit",
      "pedersenAggregateStatus",
      "pedersenAggregateHash",
      "pedersenTallyVerified",
      "pedersenTallyMessage",
      "pedersenContextHash",
      "auditHash",
      "createdAt"
    ];
    const fieldRoundTrip = persistentFieldNames.map((field) => ({
      field,
      equal: jsonEqual(loadedResponse.body.report[field], originalReport[field])
    }));
    assertCase(
      "persistence: all AggregatorReport v2 fields round-trip",
      fieldRoundTrip.every((item) => item.equal),
      { fieldRoundTrip }
    );

    return {
      sqlitePath,
      electionId,
      auditHash: loadedResponse.body.report.auditHash,
      integrityVerified: loadedResponse.body.integrityCheck.verified,
      fieldRoundTrip,
      validVoteIds: loadedResponse.body.report.validVoteIds,
      invalidVoteIds: loadedResponse.body.report.invalidVoteIds,
      proofStatus: loadedResponse.body.report.proofStatus,
      bucketTokenHashCounts: loadedResponse.body.report.partitionAudit.buckets.map(
        (bucket) => ({
          candidateId: bucket.candidateId,
          tokenHashCount: bucket.tokenHashes.length
        })
      )
    };
  } finally {
    if (firstServer) {
      stopServer(firstServer);
    }
    if (secondServer) {
      stopServer(secondServer);
    }
  }
}

async function main(): Promise<void> {
  mkdirSync(reportDir, { recursive: true });

  let server: ChildProcessWithoutNullStreams | null = null;

  try {
    server = await startApiServer({
      VERIVOTE_PERSISTENCE: "memory"
    });

    const cases = [
      await runAggregatorCase("normal", null, {
        totalVotes: 8,
        validVotes: 8,
        invalidVotes: 0,
        duplicateVotes: 0,
        receiptChainVerified: true,
        reasons: []
      }),
      await runAggregatorCase("duplicate-token", "inject-duplicate-vote", {
        totalVotes: 9,
        validVotes: 8,
        invalidVotes: 1,
        duplicateVotes: 1,
        receiptChainVerified: true,
        reasons: ["duplicate-token"]
      }),
      await runAggregatorCase("invalid-candidate", "inject-invalid-vote", {
        totalVotes: 9,
        validVotes: 8,
        invalidVotes: 1,
        duplicateVotes: 0,
        receiptChainVerified: true,
        reasons: ["invalid-candidate"]
      }),
      await runAggregatorCase("non-one-hot", "inject-non-one-hot-vote", {
        totalVotes: 9,
        validVotes: 8,
        invalidVotes: 1,
        duplicateVotes: 0,
        receiptChainVerified: true,
        reasons: ["invalid-one-hot"]
      }),
      await runAggregatorCase(
        "candidate-vector-mismatch",
        "inject-candidate-vector-mismatch",
        {
          totalVotes: 9,
          validVotes: 8,
          invalidVotes: 1,
          duplicateVotes: 0,
          receiptChainVerified: true,
          reasons: ["candidate-vector-mismatch"]
        }
      ),
      await runAggregatorCase("commitment-tamper", "tamper-commitment", {
        totalVotes: 8,
        validVotes: 7,
        invalidVotes: 1,
        duplicateVotes: 0,
        receiptChainVerified: false,
        reasons: ["commitment-opening-failed", "receipt-chain-break"]
      }),
      await runAggregatorCase("receipt-chain-delete", "delete-vote", {
        totalVotes: 7,
        validVotes: 0,
        invalidVotes: 7,
        duplicateVotes: 0,
        receiptChainVerified: false,
        reasons: ["receipt-chain-break"]
      })
    ];

    const exportSmoke = await runExportSmoke();
    const reportTamperSmoke = await runReportTamperSmoke();
    stopServer(server);
    server = null;

    const persistenceSmoke = await runPersistenceSmoke();
    const outputFile = join(reportDir, "api_smoke.json");

    writeJson(outputFile, {
      schemaVersion: "verivote.aggregator-api-smoke.v1",
      generatedBy: "pnpm aggregator:api-smoke",
      baseUrl,
      caseCount: cases.length,
      allIntegrityVerified: cases.every((item) => item.integrityVerified),
      cases,
      exportSmoke,
      reportTamperSmoke,
      persistenceSmoke
    });

    console.log(`Wrote API smoke evidence to ${join("docs", "evaluation", "aggregator_reports", basename(outputFile))}`);
  } finally {
    if (server) {
      stopServer(server);
    }
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
